### ISSUE TITLE
Script to create and deploy multiple projects from project group using the version number ?

### ISSUE THREAD

**Issue by ramreddy26** [Dalmirog/OctoPosh#140]
Hi,

First of all thanks for writing this powershell module, it is very helpful for us. If possible could you please add a script to create and deploy multiple projects from project group using the version number ?

Thanks

**Comment by Dalmirog** [comment]
Hi @ramreddy26 ! I'm glad to hear the module is helping you.

The module was initially built as a way to Get, Create and Modify Octopus resources programatically. At the moment is not in the plans to add scripts that create releases and deployments, because [Octo.exe already does that](http://docs.octopusdeploy.com/display/OD/Octo.exe+Command+Line).

What you should do is combine Octoposh and Octo.exe to achieve your goal:

```powershell
$projectGroup = Get-OctopusProjectGroup -ProjectGroupName "All projects"

foreach ($project in $projectGroup.projects){
    #use Octo.exe using $project.projectname for the project name
}

```

Cheers
