### ISSUE TITLE
Start healthcheck blows up if a machine is in more than 1 environment

### ISSUE THREAD

**Issue by Dalmirog** [Dalmirog/OctoPosh#194]
Lines: https://github.com/Dalmirog/OctoPosh/blob/master/Scripts/Start-OctopusHealthCheck.ps1#L67-L73

Gotta add a test for this.

**Comment by todthomson** [comment]
The issue is the incorrect use of the "array index" syntax on `environmentIDs` e.g.

```PowerShell
$EnvironmentID = $Machines[0].environmentIDs[0]
```

Which seems to return (for some reason?) every environment in the `ReferenceCollection` (base type `HashSet<T>`) to a space-separated string, e.g.

```
PowerShellnvironment-1 Environment-2 Environment-3"
```

Which will work fine if the machine at `$Machines[0]` is only in a single environment, but will fail if it is in multiple environments (which is what I'm seeing).

The reason is that `environmentIDs` is a `HashSet<T>` which can't be indexed as `environmentIDs[0]` as it doesn't implement `IList<T>`.

The fix is to replace the line https://github.com/Dalmirog/OctoPosh/blob/master/Scripts/Start-OctopusHealthCheck.ps1#L71 with the following:

```PowerShell
$EnvironmentID = $Machines[0].environmentIDs | Select -First 1
```

I will send that PR to `development` now.

**Comment by todthomson** [comment]
:warning: hold off on this for now, while this fixes the bug it doesn't achieve the desired outcome, I will be back asap with more fixes ;)
