### ISSUE TITLE
Does this library have an associated licence?

### ISSUE THREAD

**Issue by klagan** [Dalmirog/OctoPosh#280]
**PLEASE read this before submitting your issue**

Thanks for taking the time to log an issue.

However, I want the backlog to reflect things I'm committed to add/fix in the future. So when you reach the Project's Issues page, you wont have to swim through tons of issues created by many users, but instead only of things that you know are going to happen.

If you've found a bug or you want to propose an enhancement, please [reach out at Gitter](https://gitter.im/Dalmirog/OctoPosh#initial) instead. I'm monitoring that chat pretty often.

**Yes**, this is totally a rip off of the way the *Octopus Deploy* team handles their issues :).

**Comment by ephos** [comment]
I was looking myself and wondering the same thing.  I tend to go for MIT licensed projects as they don't need any sell or extra justification for the security or legal guys :) so fingers crossed for that!

**Comment by Dalmirog** [comment]
@klagan `Yes, this is totally a rip off of the way the Octopus Deploy team handles their issues :).`. I'm already in contact with @PaulStovell 's lawyers about this matter. Hopefully [being part of the Octopus team](https://octopus.com/company/team) will lessen the lawsuit money a bit :)

About the license, I mostly didn't add one yet because this is my first public projects and I'm still learning the ropes of the whole thing. I'll do some reading about which license I should use here during the weekend :)

**Comment by Dalmirog** [comment]
MIT license added https://github.com/Dalmirog/OctoPosh/commit/66fe5b85eacf792c9b187a3c2efcb55cc9def681
